version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/spa_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=DcIvkfOhfeIAdlvbmXRemvZoaNOBlljZ
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: DcIvkfOhfeIAdlvbmXRemvZoaNOBlljZ
      MYSQL_DATABASE: spa_db
    ports:
      - "3306:3306"